service: galpi

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  environment:
    CLIENT_ID: ${s3:galpi-${self:provider.stage}/client_id}
    CLIENT_SECRET: ${s3:galpi-${self:provider.stage}/client_secret}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
