service: galpi

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-wsgi

custom:
  customDomain:
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true
  domain:
    dev: ''
    staging: staging.api.galpi.io
    prod: api.galpi.io
  pythonRequirements:
    dockerizePip: non-linux
  wsgi:
    app: app.app
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    environment:
      CLIENT_ID: ${s3:galpi-${self:provider.stage}/client_id}
      CLIENT_SECRET: ${s3:galpi-${self:provider.stage}/client_secret}
      SECRET_KEY: ${s3:galpi-${self:provider.stage}/secret_key}
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
