service: galpi

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage}
  region: ap-northeast-1

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-wsgi

custom:
  customDomain:
    domainName: ${self:custom.domain.${opt:stage}}
    stage: ${opt:stage}
    createRoute53Record: true
  domain:
    dev: ''
    staging: staging.api.galpi.io
    prod: api.galpi.io
  pythonRequirements:
    dockerizePip: non-linux
  wsgi:
    app: galpi.app
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    environment:
      CLIENT_ID: ${ssm:/galpi/${opt:stage}/client_id}
      CLIENT_SECRET: ${ssm:/galpi/${opt:stage}/client_secret}
      SECRET_KEY: ${ssm:/galpi/${opt:stage}/secret_key}
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
