service: galpi

provider:
  name: aws
  runtime: python
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [Items, Arn] }

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local

custom:
  name: ${self:service}-${self:provider.stage}

  # Stage
  _base: &base
    domain: '<unused>'
    environment: &environment
      SECRET_KEY: ${ssm:/galpi/${self:provider.stage}/secret_key}
      CLIENT_ID: ${ssm:/galpi/${self:provider.stage}/client_id}
      CLIENT_SECRET: ${ssm:/galpi/${self:provider.stage}/client_secret}
      TABLE_PREFIX: ${self:custom.name}
  dev:
    <<: *base
    environment:
      <<: *environment
      CORS_ORIGIN: 'http://localhost:8080'
    dynamodb_seed:
      - table: ${self:custom.name}-items
        sources:
          - ./dev/items.json

  # Plugin
  customDomain:
    domainName: ${self:custom.${self:provider.stage}.domain}
    stage: ${self:provider.stage}
    createRoute53Record: true
  pythonRequirements:
    dockerizePip: non-linux
  wsgi:
    app: app.app
    packRequirements: false
  dynamodb:
    start:
      migrate: true
    seed:
      main:
        sources: ${self:custom.${self:provider.stage}.dynamodb_seed}

functions:
  app:
    handler: wsgi.handler
    environment: ${self:custom.${self:provider.stage}.environment}
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'

resources:
  Resources:
    Items:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.name}-items
        AttributeDefinitions:
          - AttributeName: owner
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: owner
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
